service: notes-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: eu-north-1

package:
  individually: true

custom:
  esbuild:
    bundle: true
    minify: true
  prune:
    automatic: true
    number: 1

functions:
  authorizer:
    environment:
      COGNITO_USERPOOL_ID: !Ref cognitoUserPool
      COGNITO_USERPOOL_WEB_CLIENT_ID: !Ref cognitoUserPoolWebClient
    handler: functions/authorizer.handler

  createNote:
    handler: functions/createNote.handler
    environment:
      NOTES_TABLE_NAME: !Ref notesTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: !GetAtt notesTable.Arn
    events:
      - http:
          method: post
          path: notes
          authorizer: authorizer

  updateNote:
    handler: functions/updateNote.handler
    environment:
      NOTES_TABLE_NAME: !Ref notesTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource: !GetAtt notesTable.Arn
    events:
      - http:
          method: put
          path: notes/{id}
          authorizer: authorizer

  deleteNote:
    handler: functions/deleteNote.handler
    environment:
      NOTES_TABLE_NAME: !Ref notesTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DeleteItem
        Resource: !GetAtt notesTable.Arn
    events:
      - http:
          method: delete
          path: notes/{id}
          authorizer: authorizer

  getAllNotes:
    handler: functions/getAllNotes.handler
    environment:
      NOTES_TABLE_NAME: !Ref notesTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Scan
        Resource: !GetAtt notesTable.Arn
    events:
      - http:
          method: get
          path: notes
          authorizer: authorizer
          # authorizer:
          #   type: COGNITO_USER_POOLS
          #   arn: !GetAtt cognitoUserPool.Arn
          #   name: userpool_authorizer

plugins:
  - serverless-esbuild
  - serverless-iam-roles-per-function
  - serverless-prune-plugin

resources:
  Resources: ${file(resources.yml)}
